# -*- mode: ruby -*-

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.synced_folder './volume', '/vagrant'
  config.vm.network "forwarded_port", guest: 2300, host: 2300

  config.vm.provision 'shell', path: './setup.sh', privileged: false
end
